# Generated by Django 4.1.2 on 2022-10-11 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_remove_quiz_duration_remove_quiz_number_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondance',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='respondance',
            name='question',
        ),
        migrations.CreateModel(
            name='ResondanceAnswer',
            fields=[
                ('responder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QuizApp.respondance')),
                ('responder_answer', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuizApp.question')),
            ],
        ),
    ]
