# Generated by Django 4.1.2 on 2022-10-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_remove_respondance_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondance',
            name='score',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='ResondanceAnswer',
        ),
    ]
